# Generated by Django 5.0.6 on 2024-06-05 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.CharField(choices=[('V', 'Virgin Galactic'), ('S', 'SpaceX'), ('B', 'Blue Origin')], default=0, max_length=1)),
                ('experiences', models.TextField(max_length=1000)),
                ('vendor', models.CharField(choices=[('V', 'Virgin Galactic'), ('S', 'SpaceX'), ('B', 'Blue Origin')], default=0, max_length=1)),
                ('max_tickets', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(verbose_name='Departure Date')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.package')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='users',
            field=models.ManyToManyField(through='main_app.Ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
