# Generated by Django 5.0.6 on 2024-06-04 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='available_tickets',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='vendor',
            field=models.CharField(choices=[('V', 'Virgin Galactic'), ('S', 'SpaceX'), ('B', 'Blue Origin')], default=0, max_length=1),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=10)),
                ('date', models.DateField(verbose_name='Departure')),
                ('flight_num', models.IntegerField(default=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.package')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
