# Generated by Django 5.0.6 on 2024-06-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_ticket_price_alter_package_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
